# SOME BASIC OPERATIONS OF NUMPY


In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


**DIMENTIONS OF THE ARRAY**


In [4]:
a.ndim

1

In [5]:
b.ndim

2

**SHAPE OF THE ARRAY**


In [6]:
a.shape

(4,)

In [7]:
b.shape

(2, 4)

**GET DATATYPE**

In [8]:
a.dtype

dtype('int64')

In [9]:
b.dtype

dtype('int64')

**ITEM SIZE**


In [10]:
#it will return the bytes for the data type of the array, for ex the data type of a is int64 so it returns as 8,if the data type is int32 then it
#would return 4 as an answer.
a.itemsize

8

In [11]:
b.itemsize

8

**TOTAL NUMBERS OF ELEMENTS**


In [12]:
a.size

4

In [13]:
b.size


8

**TOTAL NUMBERS OF BYTES**

In [14]:
a.nbytes

32

In [15]:
b.nbytes

64

# ACCESSING,CHANGING ELEMENTS ROWS AND COLUMN OF ARRAY

**WE CAN ALSO ACCESS ELEMENTS USING NEGATIVE INDEX**

In [16]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


**GETTING SPECIFIC ELEMENTS**

In [17]:
#ARRAY NAME [ROW,COLUMN]
a[1,1]

np.int64(7)

**GETTING SPECIFIC ROWS**

In [18]:
a[0,:]

array([1, 2, 3, 4, 5])

In [19]:
a[1,:]

array([ 6,  7,  8,  9, 10])

**GETTING SPECIFIC COLUMN**

In [20]:
a[:,3]

array([4, 9])

**ANOTHER METHOD**

In [21]:
# arrayname[start_index:end_index:step_size]
#here first zero refers to the first row and there it refers to the 1st element till the last one excluding with a step of 2
a[0, 0:4:2]

array([1, 3])

**CHANGNG ELEMENTS**

In [22]:
a[0,0]=100

In [23]:
print(a)

[[100   2   3   4   5]
 [  6   7   8   9  10]]


In [24]:
a[0,1]=200

In [25]:
print(a)

[[100 200   3   4   5]
 [  6   7   8   9  10]]


In [26]:
a[0,2]=300

In [27]:
print(a)

[[100 200 300   4   5]
 [  6   7   8   9  10]]


# INITILIZING DIFFERENT ARRAYS

In [28]:
# all zeros matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [29]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [30]:
# all 1s matrix of datatype of int32
np.ones((3,2),dtype='int32')

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

In [31]:
# any other numbers within the array it takes two values one is size and the other is value,this also have datatype can be added if want.
np.full((2,3),69)

array([[69, 69, 69],
       [69, 69, 69]])

In [32]:
# theres is a full_like method which takes the size of the last used array or any array created before we just need to mention the value.
np.full_like((a),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [33]:
# creating with random values.
np.random.rand(2,4)

array([[0.91567065, 0.27548388, 0.71311863, 0.79694362],
       [0.09553364, 0.22011861, 0.36176124, 0.81455414]])

In [34]:
# another method called random_sample which is like full_like method which takes the size of used array and puts random values in it.
np.random.random_sample(a.shape)

array([[0.40967798, 0.81308314, 0.67977081, 0.66757497, 0.70865645],
       [0.62283239, 0.30121439, 0.62538354, 0.40801365, 0.15231979]])

In [35]:
# identity matrix can also be created.
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
# we can also repeat an array.
arr= np.array([[1,2,3,4,5]])
r1= np.repeat(arr,4 ,axis=0)
print(r1)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


# creating a matrix without typing manually 

In [38]:
output= np.ones((5,5))
print(output)

z= np.zeros((3,3))
print(z)

z[1,1]=9
print(z)

#the 1:-1 can also be written as 1:4 which means that it starts form 1st elemnet and then till the 4th element which is the 5th row a matrix will be inserted.
output[1:-1 , 1:-1]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
