# BASIC NUMPY OPERATION

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [8]:
# so here we can see that while we are trying to copy the value of a to c and when we change the value of c the  a also gets changed.
# to prevent this we use the copy method.
c = a
c[0]=100
print(a)

[100   2   3   4   5]


In [12]:
# so when we use the copy method the original value is not changed it copys and then the change is made.
c = a.copy()
c[2]=200
print(a)
print(c)

[100   2   3   4   5]
[100   2 200   4   5]
